name: iOS Build

on:
  workflow_dispatch:

jobs:
  verify-project:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Run Expo Doctor
        run: npx expo-doctor

      - name: Generate iOS project
        run: npx expo prebuild --platform ios

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Build iOS Archive
        run: |
          cd ios

          xcodebuild archive \
            -workspace GuiGymDieta.xcworkspace \
            -scheme GuiGymDieta \
            -configuration Release \
            -archivePath build/GuiGymDieta.xcarchive \
            CODE_SIGNING_ALLOWED=NO

      - name: Create IPA
        run: |
          cd ios

          mkdir Payload

          cp -R build/GuiGymDieta.xcarchive/Products/Applications/GuiGymDieta.app Payload/

          cd Payload
          zip -r ../GuiGymDieta.ipa .
          cd ..

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: GuiGymDieta-IPA
          path: ios/GuiGymDieta.ipa